#!/usr/bin/env sh

if [[ $# != 1 ]]; then
  echo "Usage: $0 <blah.c>"
  exit 1
fi

/home/sphippen/libs/musl/bin/musl-gcc -static -o musl-repro "$1"
gcc -o glibc-repro "$1"

./musl-repro
mv out.bin musl.repro
./glibc-repro
mv out.bin glibc.repro
rm musl-repro glibc-repro
cmp musl.repro glibc.repro
