#include <stdio.h>
#include <math.h>
#include <wchar.h>

// Thanks, Josh!
#ifdef MUSL
#include "musl.h"
#define snprintf musl_snprintf
#endif

#define LEN 10000
char buf[LEN];

int main(){
    void *p = NULL;
    int n;
    wchar_t wc[10];
    wint_t wi[2];

    snprintf(buf, LEN, "%-+07.*A", 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$F", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%05.*zo", 3, 2566622753u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 8hd", 862452272);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ -*.*F", 9, 0, 38327530.7829);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+-ji", -1555963205);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$+0.7LE", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0+4La", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0*.*Lg", 7, 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-4.6s", "A;]ri-:rKV");
    printf ("%s", buf);
    snprintf(buf, LEN, "%00 2.*i", 8, 882217188);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*.*tu", 9, 6, 3292407134u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$0+9LG", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$#0#.1hhx", 777257515u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 134);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##-1.*hho", 1, 1919641836u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+.*g", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-0-8zu", 1123944988u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-0tu", 2726510929u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--8s", "09}V?WklrI");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$0.8Lf", -190400013.018);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 10, 246);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---2.*s", 0, "^^OO_)6Sm9");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-+*.*lld", 8, 6, -1926140748);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-6c", 204);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.*s", 8, "n-Rn>x|l0N");
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$###Le", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Lg", 5, -784202141.143);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$0-7tx", 467848118u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#.9Lf", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.1ju", 6, 154996703u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$+ 9zd", 330322120);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.6lX", 9, 674846651u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$++LE", -263985299.845);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0*li", 6, 1369615513);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.*LF", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.*LA", 8, 413748412.624);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.*o", 4, 2731026528u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$n", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$4ld", -423456414);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$tn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%jn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.*LE", 3, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*Lf", 1, 154398067.851);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$ E", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-#8.3o", 2111199958u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##0*.*X", 9, 10, 4152757646u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-##*a", 7, 901724158.346);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#--*tx", 4, 3282271641u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.*zu", 10, 712222046u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*c", 5, 129);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-7c", 169);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++*LE", 7, 983526121.598);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--3tx", 2854462096u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*Le", 9, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+#*.*e", 6, 9, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---10.*s", 3, "'33!mh_t+T");
    printf ("%s", buf);
    snprintf(buf, LEN, "% #*.10A", 10, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0#9.*tX", 10, 242677728u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$#5LF", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.*X", 8, 2636747222u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*E", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 1.*LG", 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-00*.*LF", 4, 10, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.10g", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$-00llu", 1847444135u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.8Lf", 9, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*f", 4, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*g", 9, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$008lu", 787851388u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*i", 9, -2066871965);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.7s", "PRJYJ/6FNI");
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1$ +-La", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
}
