#include <stdio.h>
#include <math.h>
#include <wchar.h>

// Thanks, Josh!
#ifdef MUSL
#include "musl.h"
#define snprintf musl_snprintf
#endif

#define LEN 10000
char buf[LEN];

int main(){
    void *p = NULL;
    int n;
    wchar_t wc[10];
    wint_t wi[2];

    snprintf(buf, LEN, "%#2E", 2.41532099562);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.8Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*tu", 5, 436758991u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.*ju", 3, 10, 4134275460u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#09.1lX", 241486326u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--0.0E", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 04.*Lg", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0  *G", 4, 378.453882042);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++3.*i", 6, -416610531);
    printf ("%s", buf);
    snprintf(buf, LEN, "%8zX", 4099507878u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.*a", 8, 919.511718367);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 00*.1Lf", 10, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0#4.10hho", 374482594u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.6G", 10, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*o", 5, 1290092392u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+LE", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+*.*La", 6, 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*LE", 6, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "% 3.9hhd", 1772885076);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#+a", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#*llX", 5, 1555404384u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.*zu", 10, 2, 2536263206u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0--*.0Lg", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*x", 1, 2115602350u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 2.1E", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%5llx", 1619943223u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-*hx", 1, 471664396u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--7.*hx", 1, 786249262u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+1G", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#- 6.*e", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.*llo", 8, 2, 2699062100u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5LF", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0.*zu", 2, 3239441104u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+-*.2E", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 8, 9);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Lf", 6, 658.258600409);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##02.1LG", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0 7Lf", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.8llX", 2889745592u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1ju", 2210607520u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*La", 6, 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10.*hhX", 0, 3390071980u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0*.4Lf", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10.5lld", 395525845);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-*.*a", 7, 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#3e", 652.496816169);
    printf ("%s", buf);
    snprintf(buf, LEN, "%06.9LF", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-0.*o", 1, 57629518u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#9.0La", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 -.6Lg", 870.840677874);
    printf ("%s", buf);
    snprintf(buf, LEN, "%e", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%Lf", 672.737618009);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---.*u", 10, 2566887466u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+.*Lf", 9, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.*s", 10, "MY-UgmXd02");
    printf ("%s", buf);
    snprintf(buf, LEN, "%10jx", 3128605854u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.5hhi", 6, 453017402);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-+*.*a", 5, 2, 707.897938559);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*llx", 3, 2441964939u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0+*.5e", 1, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 0*.*g", 5, 0, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%lx", 3823547368u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-8hho", 3682094900u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.7E", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5ti", 595386356);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---5c", 194);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0hhX", 3345375178u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#5e", -538.120878844);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+-5.*E", 5, -207.365578268);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.1Lf", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+++Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.8ti", 396469693);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00.*LE", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0*F", 6, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00#7jX", 4021691706u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.*A", 8, 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%3G", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# G", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.0A", 5, 799.32735393);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.0La", -396.603277523);
    printf ("%s", buf);
    snprintf(buf, LEN, "% +.8Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+8g", 259.460007438);
    printf ("%s", buf);
    snprintf(buf, LEN, "%000hhX", 244739959u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0010zX", 930360937u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*La", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.7llx", 3515211242u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-tX", 4263872108u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.6ti", 7, 1276914450);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*lu", 8, 3914241205u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 90);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*G", 10, 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-0*.7X", 7, 343782325u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+  .6LF", 38.5737369373);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.*f", 6, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-+2F", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#7.*o", 7, 242187500u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0.*hX", 0, 807832303u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*Le", 10, 7, -363.233813192);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#- *.8Le", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%n", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*LA", 6, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*ju", 2, 2157215798u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-s", "u|8!Lclt2;");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0 *LE", 7, 932.990380052);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-10c", 33);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-c", 170);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+-*.*ti", 5, 7, 308340551);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*a", 6, 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*jx", 2, 1393024878u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*hhx", 2, 4249935198u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10F", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*g", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "% +-.5G", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#- 2.1f", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%8.1s", "x<<h#%i^DG");
    printf ("%s", buf);
    snprintf(buf, LEN, "%00#7.*zo", 4, 519966013u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% +0.7G", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% - .0A", -103.120582108);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.0llu", 1, 3551149536u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*e", 2, 6, -819.198335966);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##3.9e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0lx", 4261310938u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*LA", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 9, 245);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- #4.*a", 0, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 .10i", 1623112690);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-9.9zx", 1265124575u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.*g", 1, 4, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-c", 78);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ 5.*LG", 4, -399.534626152);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-.*tx", 1, 3591286586u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.8A", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*hi", 7, 7, 380629607);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%00.10llX", 1101296017u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.0E", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.*jX", 2, 9, 3162781522u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.*LE", 10, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0--.*zu", 1, 1386800997u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*hu", 9, 6, 2590677961u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.4hhd", -1721783389);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#00.5zo", 3243866515u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--c", 12);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--0.*zu", 8, 3476355674u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0*F", 9, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.*s", 1, 1, "*Yk,c%e`m<");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-Le", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*.1LG", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%6.7G", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%6.10lu", 3374881299u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #*.6LE", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---5c", 29);
    printf ("%s", buf);
    snprintf(buf, LEN, "%3.1jo", 2754020243u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1.*zi", 5, 1555735268);
    printf ("%s", buf);
    snprintf(buf, LEN, "%jn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.9zu", 4, 608850299u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0Le", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0+*.*li", 10, 4, -653653204);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  #Le", 839.758513226);
    printf ("%s", buf);
    snprintf(buf, LEN, "%04.*lX", 0, 3255164179u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#- *LE", 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-05.*e", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*LF", 3, -417.282900153);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*u", 7, 623242270u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+01LG", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-g", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-+*.*hhd", 1, 7, 698037582);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*ju", 5, 2979946669u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---1c", 11);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .0jd", -545916353);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0##6tX", 2112680176u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*c", 1, 129);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0 6f", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+*.*G", 10, 4, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- -*.*g", 2, 6, 456.566825819);
    printf ("%s", buf);
    snprintf(buf, LEN, "%8.1LG", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%000*.3jx", 9, 3609245670u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ji", 671719163);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00#.*tx", 1, 3531789443u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0-2.*ju", 8, 2072890132u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##0.*llx", 1, 3401053990u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -8LG", -773.33285993);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#+*.*e", 4, 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%02.*ho", 1, 2896121596u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*to", 7, 3688723223u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.9u", 4, 2180969140u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "% 10.9ji", 98487601);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-- *zi", 8, -601352798);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.*hhx", 2, 706302425u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#5.*e", 1, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%03.*F", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*e", 7, 1, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7g", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--04.*g", 9, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-2.5o", 4037372651u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%n", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%007.*zx", 3, 111099738u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.7ju", 9, 3188647791u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--5.3hx", 1671339278u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .2G", 653.773900236);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 10.1A", -328.667973065);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#2.10tx", 569777468u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*Le", 1, 529.729982994);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++.10Le", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  3Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*i", 9, 811081246);
    printf ("%s", buf);
    snprintf(buf, LEN, "%05.8jX", 2870896468u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#hhX", 2985944384u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 7.4f", 643.23404753);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0a", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--c", 233);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.0llu", 2674895374u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#5.9to", 1803260609u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-5.*tu", 5, 2653945109u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+#f", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%s", "2>\\$W{@'i9");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-7.*s", 2, "x[.ChLHH*b");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0009hi", -1764098280);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-#lX", 242628040u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7llx", 3488829671u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-*.*o", 3, 8, 2425116541u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*La", 5, 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0*LF", 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Lg", 4, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.2jx", 7, 2994624882u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 4La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#llX", 2983577804u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%g", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00+.5hhi", -513404824);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*hhd", 10, 10, 1248072854);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 +.*LA", 6, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.3LE", 4, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% # 8A", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# a", 876.766284845);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0-*.*hx", 5, 0, 1983882987u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4.0Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.*s", 0, "|x1KQC`_E'");
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-1LE", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%e", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-x", 3641517570u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%ti", -887203250);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+++.*Lg", 3, 860.00216406);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%# #2g", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0.*LG", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--01Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+2ld", 1176306322);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*jd", 3, 985359410);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5a", -303.378069156);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##04.*ho", 5, 3840839206u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#7Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-*ho", 8, 2872475356u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--0*.*zx", 7, 2, 695299980u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.8d", -1555454592);
    printf ("%s", buf);
    snprintf(buf, LEN, "%###*llo", 8, 2032623035u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*td", 1, 3, 1118390283);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*ji", 9, 5, 1304418827);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 4, 99);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 6, 156);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#8.*LE", 2, 79.6474940075);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "% #0LF", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10LE", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.*a", 7, 7, 59.399311932);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#5.*lx", 6, 224060069u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-8.0Lg", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0 g", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#+1.1La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.7llx", 951554855u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Le", 4, -540.702721999);
    printf ("%s", buf);
    snprintf(buf, LEN, "%008.*La", 1, -173.722971494);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-lu", 561310717u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%6.*llX", 3, 1481115495u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*.*lu", 6, 9, 1640382492u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  +*.5LE", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ +*.*ti", 7, 8, 846417344);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.8Le", 2, -381.176220162);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+lld", 1371113867);
    printf ("%s", buf);
    snprintf(buf, LEN, "%jn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.*LF", 1, 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ -*.1LF", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ *.4Le", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #.*LA", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-.2LG", -353.901724226);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.*LA", 4, 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*zo", 6, 509879696u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.3Lf", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-ju", 4174665674u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0 7.*jd", 2, 2118335351);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-6.9zu", 1151125666u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -06.*lli", 4, -2111305259);
    printf ("%s", buf);
    snprintf(buf, LEN, "%La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.8LG", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.5hx", 8, 1823274973u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 +*hi", 10, 1387776003);
    printf ("%s", buf);
    snprintf(buf, LEN, "%e", 285.39160902);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.10f", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*jo", 3, 2699057064u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.*llx", 9, 2089396364u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+4hhd", -1208575007);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10.*f", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*Le", 6, 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.0Lg", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ .10Lg", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5llX", 2765642298u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*ti", 7, 8, -613355986);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*zx", 2, 1663547593u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-*hho", 1, 3720379082u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.8hu", 4, 2129433377u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*jX", 10, 3108948999u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# #.3LA", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-1.*LF", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#.2Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.10td", 2, -654030038);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+#5.*g", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++*.8jd", 10, -1347242754);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.5zX", 1182754297u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%9Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.*ld", 1, 1341730279);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-c", 173);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #01F", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#*.7hho", 7, 1478666080u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -*.*i", 6, 8, 2108972210);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.2LF", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  .1hhi", -2136541107);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  5li", 1481064615);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#llX", 1352518911u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.*LF", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.*tX", 1, 6, 2349475340u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-LF", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*A", 7, 8, -728.190233649);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-1c", 19);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-2.9hhX", 4047648847u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--0.0e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*lli", 8, 762650231);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.*LE", 9, 8, -674.954606265);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#3tx", 332428884u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-##*to", 10, 3664026767u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10La", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Lf", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# 07LE", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.7lld", 2, 196781337);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.*Lg", 3, 1, 537.956877979);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.4e", -738.605357712);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-0*.*F", 4, 1, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--3c", 70);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.6LE", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*La", 4, 5, 40.7759026723);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%   *.7zi", 1, -398920727);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0 *LE", 8, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*hhi", 9, -1541831329);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-ji", 930362944);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 *.*Lf", 1, 3, 793.165228872);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- +*LE", 1, -793.016407362);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.10s", 6, "t[?R?gWt+e");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#10.4f", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-1.8f", 457.943939067);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#9.*LA", 5, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%6.*a", 0, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4Lf", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 06.5ji", 594960838);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*LA", 5, 5, -425.349045951);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0++.7LE", -548.062678903);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  -.*Lf", 1, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 7, 22);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.8E", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*Lg", 8, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.0s", 10, "ib2]xxKD-a");
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+1.*g", 6, 564.485519462);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*.2g", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00.*lo", 3, 1917725997u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% --LF", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#++.7LE", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.4LG", -256.619042333);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 g", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%   Lg", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4.6LE", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4s", "]Bby]zr]*]");
    printf ("%s", buf);
    snprintf(buf, LEN, "% +5.1a", -72.6700037281);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -.*Le", 0, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#4.*E", 0, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "% ##*.3F", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# -3LG", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 2, 33);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--5.10s", "%*qHc>mvYF");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#  6.4LG", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+*.*hhi", 8, 4, 1823376476);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4.*G", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*c", 2, 211);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--07.8u", 1062082973u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+1.*LE", 5, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+6F", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*llX", 8, 2353761197u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+*.*hi", 5, 7, 1392549795);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--0*zo", 9, 283507046u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++ 10lld", -1699914186);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+-5.*A", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-.*Lg", 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0--jX", 3652518476u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+*Le", 5, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 +4LG", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*La", 10, 741.875771164);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-*LG", 7, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *Lf", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00.*lu", 8, 1403156005u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0-2.1hu", 2047762442u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%++-*ji", 7, 948258138);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.2s", 4, "$Sr,4F*GmA");
    printf ("%s", buf);
    snprintf(buf, LEN, "% -#8.5G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.7llo", 7, 2026612369u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*zu", 4, 3287037780u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# .1LA", -135.160352049);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .5Lf", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%n", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  4.3Lg", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%6a", 824.541374303);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#+.8LF", -242.105441);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%9hhx", 553276868u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0 .10Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-5zo", 3466988189u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 9, 213);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---7.8s", "(l<TvX_yLQ");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ 0*.4LG", 6, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-9.*ti", 2, 1759648950);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -3Le", -773.038351643);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.2La", 3, -588.579078511);
    printf ("%s", buf);
    snprintf(buf, LEN, "%a", -23.0579662316);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-#*.*g", 5, 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.4s", 2, "FZvf_'g1T^");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-5.*La", 5, 253.071679957);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*a", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*s", 7, 1, "^KnmLT/6 ,");
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-3zX", 1983296863u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.*hhX", 1, 2, 2263651956u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%09jx", 471071095u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-#.6g", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+ 9.6A", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*LF", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ *.*ji", 2, 8, -1849471906);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -*.*LA", 5, 0, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#-*.1jo", 1, 2787642467u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-1.4La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+2.2zi", -12317934);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.4hho", 2, 3221295826u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%s", "_P9p'?1M A");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+.0a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%000hX", 221804851u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##03.4La", -146.312576233);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#4G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #-4E", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+0A", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0+*.10a", 4, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.*A", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -+*.*Lg", 8, 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.2Lf", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.0A", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0# 6.8e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 4LG", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .1A", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00hhd", -1037498184);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-.0tx", 312790295u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#+.*a", 5, 417.969992523);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*G", 10, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*llx", 8, 2222388909u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*hX", 4, 1380919651u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ju", 2135792367u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-c", 157);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-+10Lf", -375.417806306);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  *.*F", 2, 7, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#010hX", 3336989315u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#5.*e", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.9g", 6, 31.7502358675);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+2.7a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.4lX", 2, 2808042663u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0++8hhi", -2132246491);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.9f", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.5td", -940134020);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.*i", 9, 1, -1453990898);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.4hhi", 6, 1969785137);
    printf ("%s", buf);
    snprintf(buf, LEN, "%06.8Le", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+08F", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+0.1e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0A", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-.*lld", 7, -1085119897);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-00*.*lu", 4, 1, 1713329893u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--10c", 245);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhx", 305352984u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.9Le", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*G", 7, 10, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 10.*Lf", 5, 963.387992667);
    printf ("%s", buf);
    snprintf(buf, LEN, "% g", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00+.*La", 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% # e", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.*Le", 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hhn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#.*LE", 5, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*LF", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*G", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10.*La", 4, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-LG", -378.171509222);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-0*.*x", 1, 2, 964084673u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.*e", 3, 8, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#1.*zx", 3, 2863628522u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .*i", 10, -1602969437);
    printf ("%s", buf);
    snprintf(buf, LEN, "% ##10.1Lg", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%A", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.*Le", 5, 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*a", 6, 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-10zx", 3003132754u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-6.7lX", 2855871439u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+3.4a", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 9G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*lld", 9, -994827881);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00-.4zo", 384852311u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+-*.7ld", 5, 1932795739);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.*s", 2, 10, "o6tw=a`/RH");
    printf ("%s", buf);
    snprintf(buf, LEN, "%3G", 260.910870342);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#*LG", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0.3F", -728.659879866);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0tu", 242001980u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  +1.*A", 0, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "% Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ -6.2lli", 632256466);
    printf ("%s", buf);
    snprintf(buf, LEN, "%lln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.5jX", 2711263701u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.1a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+-8F", 532.545033329);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#-9.*jX", 9, 64295113u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.1s", 7, ">RE2d=H*P7");
    printf ("%s", buf);
    snprintf(buf, LEN, "% -*.10A", 7, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% E", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+*.5lld", 5, 1232975672);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##+*.*LE", 9, 9, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -#.1LE", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  +.2ti", 1908831074);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*hhd", 7, 0, -303878675);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.*a", 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*jo", 9, 2249644252u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -.7F", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+##*f", 6, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0-*.5Lf", 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5Lg", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0#*.6hho", 1, 3880517782u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-7LF", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 2, 117);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*hu", 2, 0, 122974246u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---s", "c^G}x8wcu`");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+2.*A", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*zx", 9, 10, 1308195204u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#.*Lg", 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0# .3A", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-8.6X", 1848373140u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5Lg", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%3.10LF", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 3.*E", 10, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.*A", 1, 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*LG", 10, 1, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-9La", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "% --*.9LE", 4, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.2e", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%# *.*Le", 3, 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 3.3E", -518.743696283);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0.*zu", 0, 2629260202u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#*.*lo", 5, 7, 1324977363u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-7.*LG", 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1zo", 669525272u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.*s", 3, 8, "> <xtIn\"Y9");
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.1zu", 741948829u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.*jX", 4, 1834449994u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%jn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%.1lu", 3231879941u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 60);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0 .4Le", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*jX", 10, 4, 3197878397u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---hhu", 878786208u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%f", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.10hhu", 7, 244032745u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*c", 8, 147);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.*E", 9, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*ho", 1, 1982710289u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- *.5LA", 9, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%8.*Lg", 7, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*e", 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-#.*lX", 2, 1173615164u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10Lg", 690.696218639);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.2ho", 2860611191u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 4.*LE", 3, 585.29361823);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#+6.*g", 4, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-#3.*x", 3, 3315415681u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-7.6s", "}4FO1/6]at");
    printf ("%s", buf);
    snprintf(buf, LEN, "% -Lg", -902.988587663);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.3jx", 471558758u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*s", 1, "|;%D}:v#6'");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- .8zd", -470169195);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-##10.9e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.9E", 240.986782505);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#6.*g", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hi", 159207947);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---5c", 194);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++.*LA", 3, 251.279642691);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- *.*F", 5, 4, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #E", -995.508686919);
    printf ("%s", buf);
    snprintf(buf, LEN, "%10.8tu", 1719991641u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--8c", 197);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--7.*hhd", 1, 1683672889);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*llu", 10, 874344015u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ #*.0LF", 1, -558.604672614);
    printf ("%s", buf);
    snprintf(buf, LEN, "% +2.10lli", 1128731035);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 1, 31);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+.1f", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.4ho", 924535958u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*La", 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.6g", 3, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-0.*zx", 7, 1717347656u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.*X", 4, 1, 703372238u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.*La", 2, 401.377140052);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ju", 1196147604u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%08.4hhu", 3295687342u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%n", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.8llx", 2634754141u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%1.*hho", 0, 518592260u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-f", -346.837295986);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2hhu", 413019526u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% --.*LA", 10, -206.308026743);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+ 9.2A", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.6hhi", -1872938076);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.*f", 8, 7, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-*.*x", 8, 7, 3253127986u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0d", 863775289);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-Le", 187.277853414);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2.*LF", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.5s", 4, "Q)<6$Q_&E\\");
    printf ("%s", buf);
    snprintf(buf, LEN, "%---7.*s", 5, "kpt|i#XJio");
    printf ("%s", buf);
    snprintf(buf, LEN, "% LE", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.4jx", 1, 2010411795u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.3lli", -1365004516);
    printf ("%s", buf);
    snprintf(buf, LEN, "%06.5td", -262288108);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00#*.1lx", 6, 2842970468u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% *.4La", 9, 833.707045976);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--.*g", 8, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-0.6jx", 997392388u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+#*.*e", 4, 7, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-9.*A", 1, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -*.2E", 5, -157.295980807);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+#10LA", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#07Le", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#.*llx", 6, 3953763750u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 03ld", 991012324);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-*f", 9, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*s", 7, "!TvYf:ys@p");
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*LA", 7, 9, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0  *.8LG", 2, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00 *.*g", 2, 1, 783.945455701);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+3.5LG", 471.19661158);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*LE", 7, 1, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%ln", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--7c", 28);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.2tx", 3456411778u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*hx", 6, 906702687u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#-*Le", 3, -308.525970904);
    printf ("%s", buf);
    snprintf(buf, LEN, "%02.*g", 5, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00*tu", 8, 3214438675u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%++ 10.9F", -596.067598562);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Lf", 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.*zi", 3, 9, -760791666);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 1, 77);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#  7E", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#010.4lo", 3137362929u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.6ld", 472205112);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*LA", 9, -267.895039761);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-.3s", "er.EhK@Vde");
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.4s", 5, "X<oL)h4OQk");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-+*.*lld", 2, 1, -2116511588);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 120);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%.0LF", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*zo", 2, 75311513u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*La", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%000*.*hd", 10, 0, -90202934);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  .6LE", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*jd", 9, 1362114774);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.7LE", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*X", 4, 2958450041u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%7.5LE", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.0hd", 8, -618107650);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+-*d", 10, -87997217);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4.*hx", 0, 3120089763u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*x", 9, 531075779u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*LA", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% LA", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.5A", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%hn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0.2tu", 769622167u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0-5.6LF", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*F", 1, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%zn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#7.*e", 3, 577.283831404);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+1.*ti", 5, 1202187415);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#4e", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-00.*i", 0, -2088368421);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 203);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.3F", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#*.10tx", 9, 2287156362u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#+2.*La", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0*.*ju", 6, 10, 3949619469u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#0.*llo", 8, 239138527u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##*llX", 1, 2069772977u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%e", 353.882823283);
    printf ("%s", buf);
    snprintf(buf, LEN, "%00#*.2jX", 3, 4294876899u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 003.*ji", 6, -120812757);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-.*Lf", 2, -733.917647514);
    printf ("%s", buf);
    snprintf(buf, LEN, "%07.4G", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%   zi", 1936355700);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+ -LG", 23.396191359);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-01.8LE", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-*.1zu", 10, 2549038249u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-s", "L\\voK!XR_?");
    printf ("%s", buf);
    snprintf(buf, LEN, "%tx", 2500809843u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  +7a", -702.345846263);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4llo", 1498622199u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%---5.*s", 2, "2tt.}J9L1l");
    printf ("%s", buf);
    snprintf(buf, LEN, "%+00Le", -266.384144285);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.4LG", 5, -140.086746725);
    printf ("%s", buf);
    snprintf(buf, LEN, "% +.4a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---*.*s", 6, 1, "q86SpTKFW2");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-2c", 88);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*zx", 3, 7, 3335116468u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%- -6.*LG", 2, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-llx", 395610059u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-0*.6hX", 10, 3928842910u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*Le", 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0#*.*e", 2, 10, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*hi", 9, 3, -1528765532);
    printf ("%s", buf);
    snprintf(buf, LEN, "%2a", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "% 0 *hi", 1, 780070816);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--#jx", 1067500282u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0-.2jX", 3575727887u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.2lx", 5, 289507872u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.3LG", NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 9, 222);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-.4jX", 3471851859u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-6hho", 3183617324u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-+*.*Lg", 3, 0, -405.176781745);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#  5Lg", INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%tn", &n);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 6, 210);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0-8.10hX", 625199910u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%3.1e", 250.055352832);
    printf ("%s", buf);
    snprintf(buf, LEN, "%02.*X", 3, 197762611u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+0 .*lli", 8, 1901421273);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*La", 8, 10, 229.975971828);
    printf ("%s", buf);
    snprintf(buf, LEN, "%---1c", 211);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#.*jX", 6, 703147321u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-4zu", 2529160330u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#0#.10tX", 1190872400u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%  07.*f", 10, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-#+*.*LA", 1, 1, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+.*Lf", 4, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0+ *lli", 7, -1657834494);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*c", 9, 134);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-c", 157);
    printf ("%s", buf);
    snprintf(buf, LEN, "%C", &wi);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0--.*E", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%#-hhx", 2079063353u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .4LE", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-0.2lu", 73404406u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%S", &wc);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*lo", 3, 562201576u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%##0*LF", 3, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%+#10a", 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "% -9.*E", 0, -710.580408603);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*a", 2, 0.0);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.9lli", 1624815570);
    printf ("%s", buf);
    snprintf(buf, LEN, "%.*ji", 6, 467269799);
    printf ("%s", buf);
    snprintf(buf, LEN, "%c", 182);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--*.2llX", 4, 1516409633u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%4hhX", 4160566980u);
    printf ("%s", buf);
    snprintf(buf, LEN, "% #03.*f", 5, INFINITY);
    printf ("%s", buf);
    snprintf(buf, LEN, "% .7d", -943078472);
    printf ("%s", buf);
    snprintf(buf, LEN, "%0*.*lx", 7, 9, 4210570273u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%--+*.*Lf", 6, 8, NAN);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*.*u", 2, 3, 1761024144u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%*.*zo", 2, 5, 437586410u);
    printf ("%s", buf);
    snprintf(buf, LEN, "%-p", p);
    printf ("%s", buf);
    snprintf(buf, LEN, "%%%%%%%%");
    printf ("%s", buf);
    snprintf(buf, LEN, "%-*c", 4, 81);
    printf ("%s", buf);
}
